In [1]:
import pandas as pd
patients = pd.read_csv("../data/data_clinical_patient.txt", sep="\t", skiprows=4)
patients.head()

,PATIENT_ID,STUDY,BCR_STATUS,HISTOLOGICAL_DIAGNOSIS,AGE,SEX,OS_MONTHS,OS_STATUS,KARNOFSKY_PERFORMANCE_SCORE
0,TCGA-CS-4938,Brain Lower Grade Glioma,IGC,astrocytoma,31.0,Female,4.7,0:LIVING,90.0
1,TCGA-CS-4941,Brain Lower Grade Glioma,IGC,astrocytoma,67.0,Male,7.7,1:DECEASED,90.0
2,TCGA-CS-4942,Brain Lower Grade Glioma,IGC,astrocytoma,44.0,Female,43.9,1:DECEASED,90.0
3,TCGA-CS-4943,Brain Lower Grade Glioma,IGC,astrocytoma,37.0,Male,18.1,0:LIVING,50.0
4,TCGA-CS-4944,Brain Lower Grade Glioma,IGC,astrocytoma,50.0,Male,10.6,0:LIVING,90.0

In [2]:
patients.shape

(1122, 9)

In [3]:
samples = pd.read_csv("../data/data_clinical_sample.txt", sep="\t", skiprows=4)
samples.shape

(1122, 48)

In [4]:
data = patients.merge(samples, on="PATIENT_ID", how="inner")
data.shape

(1122, 56)

In [5]:
pd.crosstab(data["IDH_STATUS"], data["GRADE"])

GRADE        G2   G3   G4
IDH_STATUS
Mutant      195  174   37
WT           19   67  434

In [6]:
data["IDH_STATUS"].isna().sum()
data["GRADE"].isna().sum()
pd.crosstab(data["IDH_STATUS"].isna(), data["HISTOLOGICAL_DIAGNOSIS"])

HISTOLOGICAL_DIAGNOSIS,astrocytoma,glioblastoma,oligoastrocytoma,oligodendroglioma
IDH_STATUS,,,,
False,168,471,114,173
True,1,119,0,1

In [7]:
data["OS_STATUS"].value_counts()

OS_STATUS
1:DECEASED    524
0:LIVING      522
Name: count, dtype: int64

In [9]:
pd.crosstab(data["IDH_STATUS"], data["OS_STATUS"])

OS_STATUS   0:LIVING  1:DECEASED
IDH_STATUS
Mutant           337          69
WT               169         350

In [12]:
data.groupby(["IDH_STATUS", "OS_STATUS"])["OS_MONTHS"].median()

IDH_STATUS  OS_STATUS
Mutant      0:LIVING      14.2
            1:DECEASED    41.1
WT          0:LIVING       8.4
            1:DECEASED    11.1
Name: OS_MONTHS, dtype: float64

In [13]:
pd.crosstab(data["GRADE"].isna(), data["HISTOLOGICAL_DIAGNOSIS"])

HISTOLOGICAL_DIAGNOSIS,astrocytoma,glioblastoma,oligoastrocytoma,oligodendroglioma
GRADE,,,,
False,169,590,114,174

In [14]:
data[data["OS_STATUS"].isna()][["HISTOLOGICAL_DIAGNOSIS", "GRADE", "IDH_STATUS", "AGE"]].head(20)

    HISTOLOGICAL_DIAGNOSIS GRADE IDH_STATUS  AGE
153                    NaN   NaN        NaN  NaN
164                    NaN   NaN         WT  NaN
165                    NaN   NaN     Mutant  NaN
166                    NaN   NaN     Mutant  NaN
167                    NaN   NaN     Mutant  NaN
168                    NaN   NaN         WT  NaN
169                    NaN   NaN     Mutant  NaN
170                    NaN   NaN         WT  NaN
171                    NaN   NaN         WT  NaN
172                    NaN   NaN         WT  NaN
174                    NaN   NaN         WT  NaN
175                    NaN   NaN     Mutant  NaN
176                    NaN   NaN     Mutant  NaN
179                    NaN   NaN     Mutant  NaN
180                    NaN   NaN         WT  NaN
181                    NaN   NaN     Mutant  NaN
182                    NaN   NaN     Mutant  NaN
326                    NaN   NaN     Mutant  NaN
330                    NaN   NaN     Mutant  NaN
331                    NaN   NaN     Mutant  NaN

In [ ]:
|