In [8]:
import pandas as pd
patients = pd.read_csv("../data/data_clinical_patient.txt", sep="\t", skiprows=4)
patients.head()

,PATIENT_ID,STUDY,BCR_STATUS,HISTOLOGICAL_DIAGNOSIS,AGE,SEX,OS_MONTHS,OS_STATUS,KARNOFSKY_PERFORMANCE_SCORE
0,TCGA-CS-4938,Brain Lower Grade Glioma,IGC,astrocytoma,31.0,Female,4.7,0:LIVING,90.0
1,TCGA-CS-4941,Brain Lower Grade Glioma,IGC,astrocytoma,67.0,Male,7.7,1:DECEASED,90.0
2,TCGA-CS-4942,Brain Lower Grade Glioma,IGC,astrocytoma,44.0,Female,43.9,1:DECEASED,90.0
3,TCGA-CS-4943,Brain Lower Grade Glioma,IGC,astrocytoma,37.0,Male,18.1,0:LIVING,50.0
4,TCGA-CS-4944,Brain Lower Grade Glioma,IGC,astrocytoma,50.0,Male,10.6,0:LIVING,90.0

In [7]:
df.shape

(1122, 9)

In [9]:
samples = pd.read_csv("../data/data_clinical_sample.txt", sep="\t", skiprows=4)
samples.shape

(1122, 48)

In [10]:
data = patients.merge(samples, on="PATIENT_ID", how="inner")
data.shape

(1122, 56)

In [11]:
pd.crosstab(data["IDH_STATUS"], data["GRADE"])

GRADE        G2   G3   G4
IDH_STATUS
Mutant      195  174   37
WT           19   67  434

In [12]:
git add .
git commit -m "load and merge clinical data, IDH by grade crosstab"

SyntaxError: invalid syntax (1633014159.py, line 1)